kind: Secret
apiVersion: v1
metadata:
  name: {{ include "jupyterhub-ssh.fullname" . }}
  labels:
    {{- include "jupyterhub-ssh.labels" . | nindent 4 }}
type: Opaque
stringData:
  values.yaml: |
    {{- .Values | toYaml | nindent 4 }}
  hostKey: {{ .Values.hostKey | required "hostKey must be set to a valid SSH Private key" | quote }}
  hubUrl: {{ .Values.hubUrl | required "hubUrl must be set to a valid JupyterHub URL" | quote }}
  sshConnTimeout: {{ .Values.ssh.timeout | default 30 | quote }}
